use_frameworks!
source 'https://github.com/zhanghua19860221/ZHPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'ZHAlamNetWork_Example' do
  pod 'ZHAlamNetWork', :path => '../'

end
