use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'ZHAlamNetWork_Example' do
  pod 'ZHAlamNetWork', :path => '../'

  pod 'Alamofire'
  pod 'Moya'
  pod 'HandyJSON'
  pod 'Toast-Swift'

end
